// <auto-generated />
using System;
using AspNetCoreServiceBusApi2.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreServiceBusApi2.Migrations
{
    [DbContext(typeof(PayloadContext))]
    partial class PayloadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3");

            modelBuilder.Entity("AspNetCoreServiceBusApi2.Model.Payload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Goals");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Payloads");
                });
#pragma warning restore 612, 618
        }
    }
}
